# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rndDealerslink' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket'  

  # Pods for rndDealerslink
  target 'rndDealerslinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rndDealerslink-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rndDealerslink-tvOS

  target 'rndDealerslink-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
